//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class listofbidEntities : DbContext
    {
        public listofbidEntities()
            : base("name=listofbidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bidtable> bidtables { get; set; }
        public virtual DbSet<dbl> dbls { get; set; }
    
        public virtual ObjectResult<decimal> usp_highest_bidder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<decimal>("usp_highest_bidder");
        }
    
        public virtual ObjectResult<string> usp_can_bid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_can_bid");
        }
    
        public virtual ObjectResult<string> usp_show_bid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_show_bid");
        }
    
        public virtual int usp_editvar(Nullable<int> show, Nullable<int> allow)
        {
            var showParameter = show.HasValue ?
                new ObjectParameter("show", show) :
                new ObjectParameter("show", typeof(int));
    
            var allowParameter = allow.HasValue ?
                new ObjectParameter("allow", allow) :
                new ObjectParameter("allow", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_editvar", showParameter, allowParameter);
        }
    }
}
